# Generated by Django 5.2.6 on 2025-09-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('A', 'Admin'), ('C', 'Customer'), ('S', 'Seller')], default='C', max_length=1),
        ),
    ]
