# Generated by Django 5.2.6 on 2026-09-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('C', 'Customer'), ('S', 'Seller'), ('A', 'Admin')], default='C', max_length=1),
        ),
    ]
